/**
 * Created by vaio on 2015/10/22.
 */
var dataSet=[
    /* Reduced data set */
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"],
    [ "项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","JK","项目管理", "Internet Explorer 4.0", "Win 95+", 4, "X" ,"DF","GH","sd"]
];
$(document).ready(function(){
    $('#dealTable').DataTable({
        "aaData":dataSet ,
        "pagingType":'full_numbers',
        "bStateSave":true//状态保存，使用了翻页或者改变了每页显示数据数量，会保存在cookie中，下回访问时会显示上一次关闭页面时的内容。
    });
});